name: 自动构建并发布 Docker 镜像

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/ks-downloader
  GHCR_REPO: ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/ks-downloader

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 1

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@29109295f81aa9208d7d86ff1c6c12d283357339

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: 登录到 Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961bbf3da0eb5abfc19e
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录到 GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961bbf3da0eb5abfc19e
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 构建和推送 Docker 镜像到 Docker Hub 和 GHCR
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.event.release.tag_name }}
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.GHCR_REPO }}:${{ github.event.release.tag_name }}
            ${{ env.GHCR_REPO }}:latest
          provenance: false
          sbom: false